on:
  push:
    branches:
    - master

name: Python Style Checker
jobs: 
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Python Style Checker
        uses: andymckay/pycodestyle-action@0.1.3
